### PR TITLE
[WIP] Add Google OpenID Tokens

### PR DESCRIPTION
**Pull request by jjaraalm**
Adds support for Google OpenID tokens in addition to Azure. Requires HSDS support (not implemented yet).

## Usage
OpenID configuration is set either via environment variables or via the `api_key` argument. To use Google OpenID you would use the following:

```python
api_key = {
    'openid_provider': 'google',
    'client_secret': client_secret,
    'scopes': scopes
}

h5pyd.File('domain', api_key=api_key)
```
where `client_secret` is either the path to a `client_secret.json` file provided by Google or a dict with the equivalent contents. `scopes` should be set to an array of access scopes that must (at a minimum) contain `openid`. 

If `openid_provider` is not set on `api_key`, or it is set to `azure`, then Azure Active Directory is used to maintain backwards compatibility.

## Changes
- All tokens are cached in a single file, `~/.hstokencfg` instead of a single file per `app_id`. If this is undesirable, it can be changed back. 
- Token renewal is handled seamlessly, if possible, for both Azure and Google.

### CODE REVIEW

**Comment by jjaraalm** [comment]
@jreadey can you test on Azure to make sure there are no issues? I do not have access.

**Comment by jreadey** [comment]
@jjaraalm - I ran into some bugs testing with AD.  Could you look into these?  I can send you my AD config settings via email.

**Comment by jjaraalm** [comment]
@jreadey, sure. It looks like AAD also has a 30 day trial, so I'll take a
look at it tonight.

**Comment by jreadey** [comment]
@jjaraalm - ok thanks.

**Comment by jjaraalm** [comment]
This works for me getting/renewing azure tokens. If you still have errors, let me know. If I get some time I might add tests, although they couldn't be automatic.

**Comment by jreadey** [comment]
This is working for me with AD (and the supporting HSDS update).

**Comment by jreadey** [comment]
@jjaraalm - can you look at the Travis failures?  I'm able to do a "pip install google-auth-oauthlib" from a clean Python install, so not sure what the problem could be.

**Comment by jjaraalm** [comment]
Sure, I can take a look. It looks like travis logs are down right now, at least for me. I'll check back later tonight.

**Pull request merged**
