### PR TITLE
Support complex numbers

### PR DESCRIPTION
**Pull request by ajelenak-thg**
Was not able to run entire h5pyd test suite but I did test dataset read/write of complex numbers. Not tried complex numbers in attributes.

### CODE REVIEW

**Comment by jreadey** [comment]
This looks nice.

What's going on with the Travis build?  Do all the tests pass on your desktop?

**Comment by ajelenak-thg** [comment]
I could not get tests to run on my computer so am going to rely on (abuse) Travis a bit. 😞

**Comment by ajelenak-thg** [comment]
The tests pass for HSDS but fail for h5serv. The tracebacks indicate that h5json needs to be upgrade to handle NumPy's complex datatype.

**Comment by jreadey** [comment]
I've been pretty liberal with skipping the test when the server is h5serv if the feature is supported on HSDS but not h5serv.  See for example, line 34 here: https://github.com/HDFGroup/h5pyd/blob/master/test/test_table.py.

**Pull request merged**
